### PR TITLE
Update typo + filename

### PR DESCRIPTION
**Pull request by Quent-in**
So it works now :)

### CODE REVIEW

**Comment by dysk0** [comment]
tnx man :)
App submitted for QA bit I still can't see language change when the system language is set on the Français :) Any suggestions?

**Comment by Quent-in** [comment]
Does it work for Spanish?

**Comment by dysk0** [comment]
Spanish works fine :)

**Comment by Quent-in** [comment]
I have it in French now :D 
[https://framapic.org/2ulpQEVLopm5/2r70koZZ3eKX.png](https://framapic.org/2ulpQEVLopm5/2r70koZZ3eKX.png)
The About page is not localised. Many thanks for your work!

**Comment by dysk0** [comment]
Nice. Thank you a lot for your help :)

**Pull request merged**
